# Generated by Django 4.1.1 on 2022-09-15 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.person')),
                ('college', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
            bases=('myapp.person',),
        ),
    ]
