# Generated by Django 4.1.1 on 2022-09-15 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.person')),
                ('relationship', models.CharField(help_text='Father, Mother or any other relation', max_length=255)),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_related_to', to='myapp.student')),
            ],
            bases=('myapp.person',),
        ),
    ]
